formbuilder/components/EditableField.js
=> Edit a field when double clicking on it

formbuilder/actions/fieldlist.js, formbuilder/components/Default.js, formbuilder/components/EditableField.js, formbuilder/components/FieldList.js, formbuilder/components/Form.js, formbuilder/components/NotificationList.js, formbuilder/containers/FormContainer.js, formbuilder/reducers/form.js, formbuilder/styles.css, package.json
r=? @almet 
demo is deployed to http://kinto.github.io/formbuilder/
=> Draggable, reorderable widgets.

README.md
That can be useful for newcomers.
r? @n1k0
=> Add simple installation instructions.

formbuilder/components/builder/EditableField.js, formbuilder/components/builder/Form.js, formbuilder/components/builder/JsonView.js, formbuilder/config.js, formbuilder/reducers/form.js, test/components/EditableField_test.js, test/reducers/form_test.js
=> Removed field name field in form properties editor comp.

formbuilder/actions/server.js, formbuilder/components/AdminView.js, formbuilder/components/CSVDownloader.js, formbuilder/components/UserForm.js, package.json, test/actions/server_test.js, test/components/AdminView_test.js, test/components/UserForm_test.js, test/test-utils.js
A few tests needs to be written:
publishForm:
submitRecord
loadSchema
getRecords
=> Write component tests

formbuilder/containers/App.js, formbuilder/routes.js
=> Rename the fieldList prop to sidebarComponent.

formbuilder/components/Welcome.js, formbuilder/containers/App.js, formbuilder/routes.js
Based on #32.
I took the old welcome page from the daybed formbuilder and tweaked it a bit.
Let me know what you think, any enhancements are welcome!
=> Add a welcome page

formbuilder/app.js, formbuilder/components/builder/Form.js, formbuilder/containers/builder/FormContainer.js, formbuilder/reducers/serverStatus.js, formbuilder/styles.css
When submitting a form, it could be handy to have a spinner show up so that the user has some feedback about what's going on.
=> Add a spinner on form submit

formbuilder/components/Welcome.js
=> Change some wording on the welcome page

formbuilder/components/builder/Default.js, formbuilder/components/builder/FieldList.js
=> Add widgets on simple click

formbuilder/styles.css
=> Button press feedback (#48 follow up)

README.md
I was reading a bit the source code and found it a bit cryptic. As I was understanding and remembering how everything was ordered, I thought it would be a good thing to actually describe the architecture in the readme.
What do you think?
=> (WIP) Add documentation about architecture

formbuilder/components/builder/FormOptions.js, formbuilder/routes.js
It now redirects to the builder.
=> Fix the back button.

formbuilder/components/builder/Form.js, formbuilder/components/builder/TitleField.js, formbuilder/containers/builder/FormContainer.js, package.json
=> Change the TitleField of the form in order to be able to update on double click.

formbuilder/components/builder/EditableField.js, test/components/EditableField_test.js
=> Add the widgets in edit mode.

formbuilder/app.js
It's ugly and not useless for us.
r? @n1k0 @Natim @leplatrem
=> Remove the queryKey used for the history.

formbuilder/components/UserForm.js, formbuilder/routes.js, formbuilder/styles.css, test/components/UserForm_test.js
It is now centered. Replaces #66
=> Change userform styling for a better display.

formbuilder/components/builder/EditableField.js
It is way easier to understand. Thanks @DirtyF for the idea!
=> Add text next to icons.

formbuilder/components/UserForm.js
=> Update the document title on form load.

formbuilder/components/Welcome.js
* glyphicon is useless here and hurts readability
* the _start_ verb may be less scary than _create_
=> Simplify default call to action

README.md, formbuilder/components/UserForm.js, formbuilder/config.js
Not sure about the styling, what do you think? Fixes #97
=> Add a footer to the generated forms

formbuilder/reducers/form.js, package.json
Before: 2.0M, now: 398K.
Refs #102
=> Use string.js rather than slugify

formbuilder/components/builder/FieldList.js, formbuilder/containers/builder/FieldListContainer.js
=> Show form actions only when needed

formbuilder/index.prod.html
=> Add a noscript tag to show something when JavaScript is disabled

formbuilder/components/builder/Form.js
What do you think @Natouille ?
=> Better wording for the submit a form button

formbuilder/routes.js
=> Add a back button on form created

formbuilder/actions/server.js
=> Remove the 'required' property when it's an empty array

formbuilder/components/CSVDownloader.js, formbuilder/components/builder/JsonSchemaDownloader.js, formbuilder/containers/builder/JsonSchemaDownloaderContainer.js, formbuilder/routes.js
This commit add a 'Download JSON' link in "/#/builder/json" sidebar.
note: The print design is broken by the href value. We have the same issus for the download csv link.
=> issus #115 - Add the ability to save the jsonschema directly

webpack.config.prod.js
App URL domain name constant was mispelled.
This should fix #141
=> fix app URL domain name

formbuilder/components/Welcome.js
Change https link to http.
Fixes #162
=> Fix Kinto URL on welcome page

formbuilder/components/RecordCreated.js
=> Change title back to project name after submitting the form

formbuilder/components/CSVDownloader.js, package.json
=> Use a library rather than custom code for CSV output

formbuilder/app.js, formbuilder/index.prod.html, formbuilder/styles/bootswatch.less, formbuilder/styles/styles.css, formbuilder/styles/theme_overwrite.less, webpack.config.github.js, webpack.config.prod.js
Here my proposal to overwrite boostrap's themes behaviors.
In a other pr i'll convert styles.css into styles.less
=> issue 106 : checkbox spacing

README.md, devServer.js, scalingo.json
I had to make it a bit more configurable through the use of two environment variables: `HOST` and `PORT`. The defaults are still the same value, respectively `localhost` and `8080`.
=> Add one-click button to Scalingo

formbuilder/config.js
Changed config of multi checkbox field to resolve editing bug
=> #202 fixed issue editing multi checkbox field
